//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company : IEntity
    {
        public Company()
        {
            this.RelUserCompanies = new HashSet<RelUserCompany>();
            this.SalesOrders = new HashSet<SalesOrder>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
        public byte[] Ver { get; set; }
        public bool IsDeleted { get; set; }
        public int Type { get; set; }
        public string FullName { get; set; }
        public string Zip { get; set; }
    
        public virtual ICollection<RelUserCompany> RelUserCompanies { get; set; }
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
