//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Controller : IEntity
    {
        public Controller()
        {
            this.Actions = new HashSet<Action>();
            this.Previleges = new HashSet<Previlege>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] Ver { get; set; }
        public bool ForAll { get; set; }
        public string ChineseName { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
        public virtual ICollection<Previlege> Previleges { get; set; }
    }
}
