//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaikeEntities : DbContext
    {
        public MaikeEntities()
            : base("name=MaikeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Action> Actions { get; set; }
        public DbSet<Brand> Brands { get; set; }
        public DbSet<Commodity> Commodities { get; set; }
        public DbSet<CommodityType> CommodityTypes { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Controller> Controllers { get; set; }
        public DbSet<OpenTime> OpenTimes { get; set; }
        public DbSet<Previlege> Previleges { get; set; }
        public DbSet<RelCommoditySHFECode> RelCommoditySHFECodes { get; set; }
        public DbSet<RelUserCommodity> RelUserCommodities { get; set; }
        public DbSet<RelUserCompany> RelUserCompanies { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<SalesOrder> SalesOrders { get; set; }
        public DbSet<SHFECode> SHFECodes { get; set; }
        public DbSet<Stock> Stocks { get; set; }
        public DbSet<SysSetting> SysSettings { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Warehouse> Warehouses { get; set; }
    }
}
