//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelCommoditySHFECode : IEntity
    {
        public int Id { get; set; }
        public byte[] Ver { get; set; }
        public bool IsDeleted { get; set; }
        public int CommodityId { get; set; }
        public int SHFECodeId { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual SHFECode SHFECode { get; set; }
    }
}
