//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role : IEntity
    {
        public Role()
        {
            this.Users = new HashSet<User>();
            this.Previleges = new HashSet<Previlege>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public byte[] Ver { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<Previlege> Previleges { get; set; }
    }
}
