//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder : IEntity
    {
        public int Id { get; set; }
        public byte[] Ver { get; set; }
        public bool IsDeleted { get; set; }
        public int CompanyId { get; set; }
        public string Comment { get; set; }
        public decimal Quantity { get; set; }
        public int StockId { get; set; }
        public int Status { get; set; }
        public System.DateTime Date { get; set; }
        public int PricingType { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
