//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHFECode : IEntity
    {
        public SHFECode()
        {
            this.RelCommoditySHFECodes = new HashSet<RelCommoditySHFECode>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public byte[] Ver { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<bool> IsInUse { get; set; }
    
        public virtual Commodity Commodity { get; set; }
        public virtual ICollection<RelCommoditySHFECode> RelCommoditySHFECodes { get; set; }
    }
}
