//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User : IEntity
    {
        public User()
        {
            this.RelUserCommodities = new HashSet<RelUserCommodity>();
            this.RelUserCompanies = new HashSet<RelUserCompany>();
        }
    
        public int Id { get; set; }
        public byte[] Ver { get; set; }
        public bool IsDeleted { get; set; }
        public string LoginName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Password { get; set; }
        public bool IsSuper { get; set; }
        public int Type { get; set; }
        public string Mobile { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ICollection<RelUserCommodity> RelUserCommodities { get; set; }
        public virtual ICollection<RelUserCompany> RelUserCompanies { get; set; }
        public virtual Role Role { get; set; }
    }
}
